### PR TITLE
Update Liv Plot Data

### PR DESCRIPTION
**Pull request by Sumit112192**
### :pencil: Description

**Type:** :beetle: `bugfix`
Need to change the data after changing the way line_interaction_in_r is updated. PR https://github.com/tardis-sn/tardis/pull/2811.

### CODE REVIEW

**Comment by Sumit112192** [comment]
@andrewfullard

**Comment by andrewfullard** [comment]
Do you know what the difference is?

**Comment by Sumit112192** [comment]
The velocity values will be changed since the r values have changed. Don't know the exact diff data. They were generated by the pytest.

**Comment by andrewfullard** [comment]
Could you pick one file and diff it? We have docs on how to do that here https://tardis-sn.github.io/tardis/io/hdf/index.html

**Comment by Sumit112192** [comment]
> Could you pick one file and diff it? We have docs on how to do that here https://tardis-sn.github.io/tardis/io/hdf/index.html

Okay. I will do that and share the diff.

**Comment by Sumit112192** [comment]
```(tardis) sam@sam-Latitude-5480:~/TARDIS$ h5diff -v test_generate_plot_mpl__plotter_generate_plot_mpl0__.h5 tardis-regression-data/tardis/visualization/tools/tests/test_liv_plot/test_liv_plotter/test_generate_plot_mpl__plotter_generate_plot_mpl0__.h5 /plot_data_hdf/data0/block0_values```

``` 
dataset: </plot_data_hdf/data0/block0_values> and </plot_data_hdf/data0/block0_values>
size:           [20x2]           [20x2]
position        block0_values   block0_values   difference          
------------------------------------------------------------
[ 0 1 ]          167             154             13             
[ 1 1 ]          167             154             13             
[ 2 1 ]          76              85              9              
[ 3 1 ]          76              85              9              
[ 4 1 ]          34              38              4              
[ 5 1 ]          34              38              4              
6 differences found
attribute: <CLASS of </plot_data_hdf/data0/block0_values>> and <CLASS of </plot_data_hdf/data0/block0_values>>
0 differences found
attribute: <FLAVOR of </plot_data_hdf/data0/block0_values>> and <FLAVOR of </plot_data_hdf/data0/block0_values>>
0 differences found
attribute: <TITLE of </plot_data_hdf/data0/block0_values>> and <TITLE of </plot_data_hdf/data0/block0_values>>
0 differences found
attribute: <VERSION of </plot_data_hdf/data0/block0_values>> and <VERSION of </plot_data_hdf/data0/block0_values>>
0 differences found
attribute: <transposed of </plot_data_hdf/data0/block0_values>> and <transposed of </plot_data_hdf/data0/block0_values>>
0 differences found
```

**Comment by Sumit112192** [comment]
Is there a way to make it more human-readable? @andrewfullard

**Review by andrewfullard — APPROVED** [review]

**Pull request merged**
